name: fruit_hub
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_asset_gen: ^0.3.0
  flutter_launcher_icons: ^0.14.4
  flutter_svg: any

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/apple.png"
  min_sdk_android: 21

flutter_assets:
  assets_path: assets/images/
  output_path: lib/core/utils
  filename: imagess.dart
  field_prefix: null
